apiVersion: 1

datasources:
  - name: FordLogger
    uid: FordLogger
    type: postgres
    url: db:5432
    database: fordlogger
    user: fordlogger
    secureJsonData:
      password: fordlogger
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
